# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_cosin <- function(alpha, a_sigma, a_y, a_yp1, a_theta, Beta, b_sigma, b0, b1, burn, b_theta, d, eta, GammaB, GammaT, kmax, kstar, Lambda, Lambda_star, last, logit, nrun, out, Phi, Plam, prec_gammaT, prec_beta, pred, prob, ps, p_constant, rho, sd_gammaB, sp, start_adapt, thin, uu, v, verbose, w, wT, wB, x, xnull) {
    .Call(`_cosin_Rcpp_cosin`, alpha, a_sigma, a_y, a_yp1, a_theta, Beta, b_sigma, b0, b1, burn, b_theta, d, eta, GammaB, GammaT, kmax, kstar, Lambda, Lambda_star, last, logit, nrun, out, Phi, Plam, prec_gammaT, prec_beta, pred, prob, ps, p_constant, rho, sd_gammaB, sp, start_adapt, thin, uu, v, verbose, w, wT, wB, x, xnull)
}

#' Sample from a truncated normal distribution. Samples are drawn
#' componentwise, so each component of the vector is allowed its own
#' mean, standard deviation, and upper and lower limits. The components
#' are assumed to be independent.
#'
#' @param y_lower \code{n x p} matrix of lower endpoints
#' @param y_upper \code{n x p} matrix of upper endpoints
#' @param mu \code{n x p} matrix of conditional expectations
#' @param sigma \code{p x 1} vector of conditional standard deviations
#' @param u_rand \code{n x p} matrix of uniform random variables
#'
#' @return z_star \code{n x p} draw from the truncated normal distribution
#'
#' @note This function uses \code{Rcpp} for computational efficiency.
#'
truncnorm_lg <- function(y_lower, y_upper, mu, sigma, u_rand) {
    .Call(`_cosin_truncnorm_lg`, y_lower, y_upper, mu, sigma, u_rand)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_cosin_rcpp_pgdraw`, b, c)
}

samplepg <- function(z) {
    .Call(`_cosin_samplepg`, z)
}

